name: Build Windows Executable
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --noconsole --name "Ship.exe" ship.py
          ls dist/  # 确认文件生成

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ship-Windows
          path: dist/Ship.exe
