name: Build Windows Executable
on: [push]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install cx_Freeze
          pip install -r requirements.txt

      - name: Build .exe with cx_Freeze
        run: python setup.py build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ship-Windows
          path: build/
