name: Build Windows Executable
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build .exe
        run: pyinstaller --onefile --noconsole --name "Ship.exe" ship.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ship-Windows
          path: dist/Ship.exe
